apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:v1.24.0-p0
          ports:
            - containerPort: 6432
          volumeMounts:
            - name: config
              mountPath: /etc/pgbouncer/pgbouncer.ini
              subPath: pgbouncer.ini
            - name: users
              mountPath: /etc/pgbouncer/users.txt
              subPath: users.txt
      volumes:
        - name: config
          configMap:
            name: pgbouncer-config
            items:
              - key: pgbouncer.ini
                path: pgbouncer.ini
        - name: users
          secret:
            secretName: pgbouncer-users
            items:
              - key: users.txt
                path: users.txt
